# Generated by Django 4.2.3 on 2023-11-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_suscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juegos',
            fields=[
                ('juegos_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
