# Generated by Django 4.2.3 on 2023-11-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0004_juegos'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='img_url',
            field=models.ImageField(default=1, upload_to='imgJuegos'),
            preserve_default=False,
        ),
    ]
